Add timetable for the COVID-19 period
BusHanyang/ERICA_shuttlecock_API pull request #18
Opened 2020-10-09 06:22 UTC by YusunPark

- The timetable for the semester has been changed because of the Corona virus.
  - Week
    - 08:00~19:00 =>10-minute interval
    - 19:00~22:00 =>30-minute interval
  - Weekend
    - 09:00~22:00 =>60-minute interval

2020-10-09 06:31 UTC, CXZ7720 commented
The directory name must not be changed. remove COVID at directory name.

2020-10-09 06:32 UTC, CXZ7720 requested changes
do not change the source directory name

2020-10-09 06:35 UTC, YusunPark commented
I named it 'semester_covid19' because it was a temporary timetable.
I'll change it.

2020-10-09 07:18 UTC, Taewan-P requested changes
As requested.

We are really not sure about the 2205 bus & weekend bus start time for now.

2020-10-09 07:18 UTC, Taewan-P commented on timetable/semester/weekend/Shuttlecock_I_weekend.json
>    "shuttlecock_i_weekend": [
This schedule is for Shuttlecock inbound. All the types should be "R", meaning Residence.

2020-10-09 07:18 UTC, Taewan-P commented on timetable/semester/weekend/Residence_weekend.json
> -    { "time": "07:45", "type": "C" },
.

2020-10-09 07:18 UTC, Taewan-P commented on timetable/semester/week/YesulIn_week.json
> +    { "time": "22:05", "type": "" }
This one too. We need to figure out whether 2205 is a valid bus schedule.

2020-10-11 07:50 UTC, Taewan-P requested changes
* Found out that weekend shuttle starts at 8.
* Buses at shuttlecock_i that arrives before 10 should be marked as type "NA"

2020-10-11 07:52 UTC, Taewan-P commented on timetable/semester/week/YesulIn_week.json
> +    { "time": "22:05", "type": "" }
Found out this 2205 is valid.

2020-10-11 07:57 UTC, Taewan-P approved these changes
LGTM.

2020-10-11 07:57 UTC, Taewan-P commented on timetable/semester/weekend/YesulIn_weekend.json
> -    { "time": "08:05", "type": "" },
Starts at 8

2020-10-11 08:01 UTC, Taewan-P approved these changes

2020-10-11 08:02 UTC, CXZ7720 approved these changes

2020-10-11 08:02 UTC, merged